### PR TITLE
refactor(pkg): remove canvas & jsdom

### PR DESCRIPTION
**Pull request by Ghustavh97**

### CODE REVIEW

**Comment by yisibl** [comment]
Does this library need to be considered for use in the browser?

**Comment by Ghustavh97** [comment]
@yisibl Yes, canvas was a pain to install and no, I personally do not plan on making it usable for browser because it does not fit my use case but I welcome pull requests that want to add that feature.

**Comment by yisibl** [comment]
I recommend using [@resvg/resvg-js](https://github.com/yisibl/resvg-js) for a little better performance.

**Comment by Ghustavh97** [comment]
@yisibl Feel free to open a PR with the switch to resvg. I think its just changing one line and removing svg2png-wasm then running tests.

https://github.com/oslllo/svg2/blob/621bd22f28cceb60390319275440cac5c1757ec6/src/svg.js#L91

**Pull request merged**
